<?php
declare(strict_types=1);

// Chocomilk SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ChocomilkUtility::setRegistrar(function (ChocomilkUtility $u): void {
    $u->clean = [ChocomilkClean::class, 'call'];
    $u->done = [ChocomilkDone::class, 'call'];
    $u->make_error = [ChocomilkMakeError::class, 'call'];
    $u->feature_add = [ChocomilkFeatureAdd::class, 'call'];
    $u->feature_hook = [ChocomilkFeatureHook::class, 'call'];
    $u->feature_init = [ChocomilkFeatureInit::class, 'call'];
    $u->fetcher = [ChocomilkFetcher::class, 'call'];
    $u->make_fetch_def = [ChocomilkMakeFetchDef::class, 'call'];
    $u->make_context = [ChocomilkMakeContext::class, 'call'];
    $u->make_options = [ChocomilkMakeOptions::class, 'call'];
    $u->make_request = [ChocomilkMakeRequest::class, 'call'];
    $u->make_response = [ChocomilkMakeResponse::class, 'call'];
    $u->make_result = [ChocomilkMakeResult::class, 'call'];
    $u->make_point = [ChocomilkMakePoint::class, 'call'];
    $u->make_spec = [ChocomilkMakeSpec::class, 'call'];
    $u->make_url = [ChocomilkMakeUrl::class, 'call'];
    $u->param = [ChocomilkParam::class, 'call'];
    $u->prepare_auth = [ChocomilkPrepareAuth::class, 'call'];
    $u->prepare_body = [ChocomilkPrepareBody::class, 'call'];
    $u->prepare_headers = [ChocomilkPrepareHeaders::class, 'call'];
    $u->prepare_method = [ChocomilkPrepareMethod::class, 'call'];
    $u->prepare_params = [ChocomilkPrepareParams::class, 'call'];
    $u->prepare_path = [ChocomilkPreparePath::class, 'call'];
    $u->prepare_query = [ChocomilkPrepareQuery::class, 'call'];
    $u->graphql_body = [ChocomilkGraphql::class, 'body'];
    $u->graphql_errors = [ChocomilkGraphql::class, 'errors'];
    $u->result_basic = [ChocomilkResultBasic::class, 'call'];
    $u->result_body = [ChocomilkResultBody::class, 'call'];
    $u->result_headers = [ChocomilkResultHeaders::class, 'call'];
    $u->transform_request = [ChocomilkTransformRequest::class, 'call'];
    $u->transform_response = [ChocomilkTransformResponse::class, 'call'];
});
